import SEO from "@/components/SEO"

export default function DisclaimerPage() {
    return (
        <div className="container max-w-4xl py-12 px-4">
            <SEO title="Legal Disclaimer - ANW" />
            <div className="prose dark:prose-invert max-w-none">
                <h1>Legal Disclaimer</h1>

                <div className="bg-yellow-500/10 border-l-4 border-yellow-500 p-4 my-8">
                    <p className="font-bold text-yellow-600 dark:text-yellow-400 m-0">
                        IMPORTANT: ANW is an advisory tool, not a guarantee.
                    </p>
                </div>

                <h2>1. No Guarantee of Accuracy</h2>
                <p>
                    The analysis provided by ANW is generated by Artificial Intelligence and based on available data patterns. While we strive for high accuracy, <strong>we cannot guarantee 100% detection of all scams or false positives.</strong>
                </p>
                <p>
                    A result of "Safe" does not guarantee that a URL or message is completely free of risk. Conversely, a "Warning" does not legally prove criminal intent.
                </p>

                <h2>2. Limitation of Liability</h2>
                <p>
                    To the maximum extent permitted by law, ANW and its affiliates shall not be liable for any direct, indirect, incidental, consequential, or special damages arising out of or in any way connected with your use of this service.
                </p>
                <p>
                    <strong>You are solely responsible for your financial decisions and actions.</strong> We are not responsible for any financial losses, data breaches, or damages resulting from reliance on our analysis.
                </p>

                <h2>3. Not Financial or Legal Advice</h2>
                <p>
                    The content and tools provided by ANW do not constitute financial, legal, or professional advice. Always consult with qualified professionals or relevant authorities (e.g., police, bank) before making significant decisions regarding suspicious activities.
                </p>

                <h2>4. Third-Party Links</h2>
                <p>
                    Our service may analyze or contain links to third-party websites. We are not responsible for the content, privacy policies, or practices of any third-party sites or services.
                </p>
            </div>
        </div>
    )
}
